spring.application.name=ms-mascotas
server.port=8082

# Conexión a MongoDB (Sin el 'data' para evitar el Deprecated)
spring.data.mongodb.uri=mongodb://brayan:password123@localhost:27017/db_mascotas?authSource=admin
spring.data.mongodb.auto-index-creation=true

# Registro en Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Seguridad y Swagger
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Configuración de RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Feign y Resilience4j
spring.cloud.openfeign.circuitbreaker.enabled=true
resilience4j.circuitbreaker.instances.ms-usuarios.slidingWindowSize=10
resilience4j.circuitbreaker.instances.ms-usuarios.failureRateThreshold=50
resilience4j.circuitbreaker.instances.ms-usuarios.waitDurationInOpenState=10s

management.endpoints.web.exposure.include=*
management.endpoint.info.access=unrestricted
management.endpoint.health.show-details=always