# Nombre del microservicio
spring.application.name=ms-usuarios
server.port=8081

# Conexión automática a PostgreSQL (Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/db_usuarios
spring.datasource.username=brayan
spring.datasource.password=password123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Desactivar seguridad temporalmente (Para que no te pida login mañana al probar)
spring.security.user.name=admin
spring.security.user.password=admin
# En el 25% inicial, permitiremos acceso total para probar Swagger
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration, org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration, org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# Configuración de Swagger (Documentación automática)
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Registro en Eureka (Lo dejaremos listo aunque no tengas el servidor Eureka aún)
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/