# Nombre del microservicio
spring.application.name=ms-usuarios
server.port=8081

# Conexión automática a PostgreSQL (Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/db_usuarios
spring.datasource.username=brayan
spring.datasource.password=password123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Desactivar seguridad temporalmente (Para que no te pida login mañana al probar)
spring.security.user.name=admin
spring.security.user.password=admin

# Configuración de Swagger (Documentación automática)
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Registro en Eureka (Lo dejaremos listo aunque no tengas el servidor Eureka aún)
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# JWT Secret Key compartida con API Gateway
jwt.secret=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b